# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385ace379ac21079fa2517f020d66b4d630c51e34ef8dbf4d2012ca56053da8ed378f56d93bccaac1350f60b3a9172b66a14d8088811f15b4c9b22c3d33ac521

test:
  secret_key_base: 0f09045595460a7d44a4dd886b9d154455cd129a45db9bd7fd317972d77383047400f3176ac34be4274691581bd79eb6f487ca568b6714cabdac65a1968b2010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
